apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-devops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-devops-app
  template:
    metadata:
      labels:
        app: cloud-devops-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: cloud-devops-app
          image: rahul0941/cloud-devops-app
          ports:
            - containerPort: 8080

