apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-devops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-devops-app
  template:
    metadata:
      labels:
        app: cloud-devops-app
    spec:
      containers:
      - name: app-container
        image: rahul0941/cloud-devops-app:latest
        ports:
        - containerPort: 80
