apiVersion: v1
kind: Service
metadata:
  name: cloud-devops-service
spec:
  type: NodePort
  selector:
    app: cloud-devops-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008  # optional custom port
